### ISSUE TITLE
Create a metadata record

### ISSUE THREAD

**Issue by LuciaSegovia** [eblondel/geonapi#11]
I can't get the 'create a metadata record' piece of code running

`mdfile <- system.file("extdata/examples", "metadata.xml", package = "geonapi")

created = GN$insertMetadata(file = mdfile, group = "1", category = "datasets")

config <- GNPrivConfiguration$new()

config$setPrivileges("all", c("view","dynamic","featured"))

GN$setPrivConfiguration(id = created, config = config)

`

The object 'created' is NULL(empty)

Any idea why is this happening?

Thanks!!

**Comment by eblondel** [comment]
@LuciaSegovia The first thing to check is the operation performed behind the R code. For that you should enable logger = "DEBUG" when creating the ``GNManager``. When running the ``insertmetadata`` R will print more verbose logs on the atual http operation that is performed to insert the metadata. Once you get this can you paste it here?
Thanks

**Comment by LuciaSegovia** [comment]
Thanks for the reply! I have done it and this is what I got:


mdfile <- system.file("extdata/examples", "metadata.xml", package = "geonapi")
> 
> created = GN$insertMetadata(file = mdfile, group = "1", category = "datasets")
[geonapi][INFO] Inserting metadata ... 
-> POST /geonetwork/srv/eng/xml.metadata.insert HTTP/1.1
-> Host: metadata.micronutrient.support
-> Accept-Encoding: deflate, gzip
-> Cookie: JSESSIONID=E0DF3DF40E0A6E77BF5095EC8B7B7BD7; XSRF-TOKEN=0195e0a7-48e4-40a0-a308-6fe1aa20be05; sessionExpiry=1609842517032; serverTime=1609842517032
-> Accept: application/json, text/xml, application/xml, */*
-> User-Agent: geonapi-0.4
-> Content-type: text/xml
-> Authorization: Basic bHVjaWE6MDIvSnVuLzE5ODc=
-> X-XSRF-TOKEN: 0195e0a7-48e4-40a0-a308-6fe1aa20be05
-> Content-Length: 18980
-> 
>> <request><data><![CDATA[<gmd:MD_Metadata xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gfc="http://www.isotc211.org/2005/gfc" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:gml="http://www.opengis.net/gml/3.2"> <gmd:fileIdentifier> <gco:CharacterString>my-metadata-identifier</gco:CharacterString> </gmd:fileIdentifier> <gmd:language> <gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/" codeListValue="eng" codeSpace="ISO 639-2"/> </gmd:language> <gmd:characterSet> <gmd:MD_CharacterSetCode codeList="http://www.isotc211.org/2005/resources/Codelist/ML_gmxCodelists.xml#MD_CharacterSetCode" codeListValue="utf8"/> </gmd:characterSet> <gmd:parentIdentifier> <gco:CharacterString>my-parent-metadata-identifier</gco:CharacterString> </gmd:parentIdentifier> <gmd:hierarchyLevel> <gmd:MD_ScopeCode codeList="http://www.isotc211.org/2005/resources/Codelist/ML_gmxCodelists.xml#MD_ScopeCode" codeListValue="dataset" codeSpace="ISOTC211/19115"/> </gmd:hierarchyLevel> <gmd:contact> <gmd:CI_ResponsibleParty> <gmd:individualName> <gco:CharacterString>someone1</gco:CharacterString> </gmd:individualName> <gmd:organisationName> <gco:CharacterString>somewhere</gco:CharacterString> </gmd:organisationName> <gmd:positionName> <gco:CharacterString>someposition1</gco:CharacterString> </gmd:positionName> <gmd:contactInfo> <gmd:CI_Contact> <gmd:phone> <gmd:CI_Telephone> <gmd:voice> <gco:CharacterString>myphonenumber1</gco:CharacterString> </gmd:voice> <gmd:facsimile> <gco:CharacterString>myfacsimile1</gco:CharacterString> </gmd:facsimile> </gmd:CI_Telephone> </gmd:phone> <gmd:address> <gmd:CI_Address> <gmd:deliveryPoint> <gco:CharacterString>theaddress</gco:CharacterString> </gmd:deliveryPoint> <gmd:city> <gco:CharacterString>thecity</gco:CharacterString> </gmd:city> <gmd:postalCode> <gco:CharacterString>111</gco:CharacterString> </gmd:postalCode> <gmd:country> <gco:CharacterString>France</gco:CharacterString> </gmd:country> <gmd:electronicMailAddress> <gco:CharacterString>someone@theorg.org</gco:CharacterString> </gmd:electronicMailAddress> </gmd:CI_Address> </gmd:address> <gmd:onlineResource> <gmd:CI_OnlineResource> <gmd:linkage> <gmd:URL>http://somelink</gmd:URL> </gmd:linkage> <gmd:name> <gco:CharacterString>someresourcename</gco:CharacterString> </gmd:name> </gmd:CI_OnlineResource> </gmd:onlineResource> </gmd:CI_Contact> </gmd:contactInfo> <gmd:role> <gmd:CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue="pointOfContact" codeSpace="ISOTC211/19115"/> </gmd:role> </gmd:CI_ResponsibleParty> </gmd:contact> <gmd:contact> <gmd:CI_ResponsibleParty> <gmd:individualName> <gco:CharacterString>someone2</gco:CharacterString> </gmd:individualName> <gmd:organisationName> <gco:CharacterString>somewhere</gco:CharacterString> </gmd:organisationName> <gmd:positionName> <gco:CharacterString>someposition2</gco:CharacterString> </gmd:positionName> <gmd:contactInfo> <gmd:CI_Contact> <gmd:phone> <gmd:CI_Telephone> <gmd:voice> <gco:CharacterString>myphonenumber2</gco:CharacterString> </gmd:voice> <gmd:facsimile> <gco:CharacterString>myfacsimile2</gco:CharacterString> </gmd:facsimile> </gmd:CI_Telephone> </gmd:phone> <gmd:address> <gmd:CI_Address> <gmd:deliveryPoint> <gco:CharacterString>theaddress</gco:CharacterString> </gmd:deliveryPoint> <gmd:city> <gco:CharacterString>thecity</gco:CharacterString> </gmd:city> <gmd:postalCode> <gco:CharacterString>111</gco:CharacterString> </gmd:postalCode> <gmd:country> <gco:CharacterString>France</gco:CharacterString> </gmd:country> <gmd:electronicMailAddress> <gco:CharacterString>someone@theorg.org</gco:CharacterString> </gmd:electronicMailAddress> </gmd:CI_Address> </gmd:address> <gmd:onlineResource> <gmd:CI_OnlineResource> <gmd:linkage> <gmd:URL>http://somelink</gmd:URL> </gmd:linkage> <gmd:name> <gco:CharacterString>someresourcename</gco:CharacterString> </gmd:name> </gmd:CI_OnlineResource> </gmd:onlineResource> </gmd:CI_Contact> </gmd:contactInfo> <gmd:role> <gmd:CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue="pointOfContact" codeSpace="ISOTC211/19115"/> </gmd:role> </gmd:CI_ResponsibleParty> </gmd:contact> <gmd:dateStamp> <gco:DateTime>2015-01-01T01:00:00</gco:DateTime> </gmd:dateStamp> <gmd:metadataStandardName> <gco:CharacterString>ISO 19115:2003/19139</gco:CharacterString> </gmd:metadataStandardName> <gmd:metadataStandardVersion> <gco:CharacterString>1.0</gco:CharacterString> </gmd:metadataStandardVersion> <gmd:dataSetURI> <gco:CharacterString>my-dataset-identifier</gco:CharacterString> </gmd:dataSetURI> <gmd:referenceSystemInfo> <gmd:MD_ReferenceSystem> <gmd:referenceSystemIdentifier> <gmd:RS_Identifier> <gmd:code> <gco:CharacterString>4326</gco:CharacterString> </gmd:code> <gmd:codeSpace> <gco:CharacterString>EPSG</gco:CharacterString> </gmd:codeSpace> </gmd:RS_Identifier> </gmd:referenceSystemIdentifier> </gmd:MD_ReferenceSystem> </gmd:referenceSystemInfo> <gmd:identificationInfo> <gmd:MD_DataIdentification> <gmd:citation> <gmd:CI_Citation> <gmd:title> <gco:CharacterString>sometitle</gco:CharacterString> </gmd:title> <gmd:date> <gmd:CI_Date> <gmd:date> <gco:Date>2015-01-01</gco:Date> </gmd:date> <gmd:dateType> <gmd:CI_DateTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication" codeSpace="ISOTC211/19115"/> </gmd:dateType> </gmd:CI_Date> </gmd:date> <gmd:edition> <gco:CharacterString>1.0</gco:CharacterString> </gmd:edition> <gmd:editionDate> <gco:Date>2015-01-01</gco:Date> </gmd:editionDate> <gmd:identifier> <gmd:MD_Identifier> <gmd:code> <gco:CharacterString>identifier</gco:CharacterString> </gmd:code> </gmd:MD_Identifier> </gmd:identifier> <gmd:citedResponsibleParty> <gmd:CI_ResponsibleParty> <gmd:individualName> <gco:CharacterString>someone</gco:CharacterString> </gmd:individualName> <gmd:organisationName> <gco:CharacterString>somewhere</gco:CharacterString> </gmd:organisationName> <gmd:positionName> <gco:CharacterString>someposition</gco:CharacterString> </gmd:positionName> <gmd:contactInfo> <gmd:CI_Contact> <gmd:phone> <gmd:CI_Telephone> <gmd:voice> <gco:CharacterString>myphonenumber</gco:CharacterString> </gmd:voice> <gmd:facsimile> <gco:CharacterString>myfacsimile</gco:CharacterString> </gmd:facsimile> </gmd:CI_Telephone> </gmd:phone> <gmd:address> <gmd:CI_Address> <gmd:deliveryPoint> <gco:CharacterString>theaddress</gco:CharacterString> </gmd:deliveryPoint> <gmd:city> <gco:CharacterString>thecity</gco:CharacterString> </gmd:city> <gmd:postalCode> <gco:CharacterString>111</gco:CharacterString> </gmd:postalCode> <gmd:country> <gco:CharacterString>France</gco:CharacterString> </gmd:country> <gmd:electronicMailAddress> <gco:CharacterString>someone@theorg.org</gco:CharacterString> </gmd:electronicMailAddress> </gmd:CI_Address> </gmd:address> <gmd:onlineResource> <gmd:CI_OnlineResource> <gmd:linkage> <gmd:URL>http://somelink</gmd:URL> </gmd:linkage> <gmd:name> <gco:CharacterString>somename</gco:CharacterString> </gmd:name> </gmd:CI_OnlineResource> </gmd:onlineResource> </gmd:CI_Contact> </gmd:contactInfo> <gmd:role> <gmd:CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue="pointOfContact" codeSpace="ISOTC211/19115"/> </gmd:role> </gmd:CI_ResponsibleParty> </gmd:citedResponsibleParty> <gmd:presentationForm> <gmd:CI_PresentationFormCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_PresentationFormCode" codeListValue="mapDigital" codeSpace="ISOTC211/19115"/> </gmd:presentationForm> </gmd:CI_Citation> </gmd:citation> <gmd:abstract> <gco:CharacterString>abstract</gco:CharacterString> </gmd:abstract> <gmd:purpose> <gco:CharacterString>purpose</gco:CharacterString> </gmd:purpose> <gmd:credit> <gco:CharacterString>credit1</gco:CharacterString> </gmd:credit> <gmd:credit> <gco:CharacterString>credit2</gco:CharacterString> </gmd:credit> <gmd:status> <gmd:MD_ProgressCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ProgressCode" codeListValue="completed"/> </gmd:status> <gmd:status> <gmd:MD_ProgressCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ProgressCode" codeListValue="valid"/> </gmd:status> <gmd:pointOfContact> <gmd:CI_ResponsibleParty> <gmd:individualName> <gco:CharacterString>someone</gco:CharacterString> </gmd:individualName> <gmd:organisationName> <gco:CharacterString>somewhere</gco:CharacterString> </gmd:organisationName> <gmd:positionName> <gco:CharacterString>someposition</gco:CharacterString> </gmd:positionName> <gmd:contactInfo> <gmd:CI_Contact> <gmd:phone> <gmd:CI_Telephone> <gmd:voice> <gco:CharacterString>myphonenumber</gco:CharacterString> </gmd:voice> <gmd:facsimile> <gco:CharacterString>myfacsimile</gco:CharacterString> </gmd:facsimile> </gmd:CI_Telephone> </gmd:phone> <gmd:address> <gmd:CI_Address> <gmd:deliveryPoint> <gco:CharacterString>theaddress</gco:CharacterString> </gmd:deliveryPoint> <gmd:city> <gco:CharacterString>thecity</gco:CharacterString> </gmd:city> <gmd:postalCode> <gco:CharacterString>111</gco:CharacterString> </gmd:postalCode> <gmd:country> <gco:CharacterString>France</gco:CharacterString> </gmd:country> <gmd:electronicMailAddress> <gco:CharacterString>someone@theorg.org</gco:CharacterString> </gmd:electronicMailAddress> </gmd:CI_Address> </gmd:address> <gmd:onlineResource> <gmd:CI_OnlineResource> <gmd:linkage> <gmd:URL>http://somelink</gmd:URL> </gmd:linkage> <gmd:name> <gco:CharacterString>somename</gco:CharacterString> </gmd:name> </gmd:CI_OnlineResource> </gmd:onlineResource> </gmd:CI_Contact> </gmd:contactInfo> <gmd:role> <gmd:CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue="pointOfContact" codeSpace="ISOTC211/19115"/> </gmd:role> </gmd:CI_ResponsibleParty> </gmd:pointOfContact> <gmd:resourceMaintenance> <gmd:MD_MaintenanceInformation> <gmd:maintenanceAndUpdateFrequency> <gmd:MD_MaintenanceFrequencyCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_MaintenanceFrequencyCode" codeListValue="daily" codeSpace="ISOTC211/19115"/> </gmd:maintenanceAndUpdateFrequency> </gmd:MD_MaintenanceInformation> </gmd:resourceMaintenance> <gmd:graphicOverview> <gmd:MD_BrowseGraphic> <gmd:fileName> <gco:CharacterString>http://wwww.somefile.org/png1</gco:CharacterString> </gmd:fileName> <gmd:fileDescription> <gco:CharacterString>Map Overview 1</gco:CharacterString> </gmd:fileDescription> <gmd:fileType> <gco:CharacterString>image/png</gco:CharacterString> </gmd:fileType> </gmd:MD_BrowseGraphic> </gmd:graphicOverview> <gmd:descriptiveKeywords> <gmd:MD_Keywords> <gmd:keyword> <gco:CharacterString>keyword1</gco:CharacterString> </gmd:keyword> <gmd:keyword> <gco:CharacterString>keyword2</gco:CharacterString> </gmd:keyword> <gmd:type> <gmd:MD_KeywordTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="theme" codeSpace="ISOTC211/19115"/> </gmd:type> <gmd:thesaurusName> <gmd:CI_Citation> <gmd:title> <gco:CharacterString>General</gco:CharacterString> </gmd:title> <gmd:date> <gmd:CI_Date> <gmd:date> <gco:Date>2015-01-01</gco:Date> </gmd:date> <gmd:dateType> <gmd:CI_DateTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication" codeSpace="ISOTC211/19115"/> </gmd:dateType> </gmd:CI_Date> </gmd:date> </gmd:CI_Citation> </gmd:thesaurusName> </gmd:MD_Keywords> </gmd:descriptiveKeywords> <gmd:resourceConstraints> <gmd:MD_LegalConstraints> <gmd:useLimitation> <gco:CharacterString>limitation1</gco:CharacterString> </gmd:useLimitation> <gmd:useLimitation> <gco:CharacterString>limitation2</gco:CharacterString> </gmd:useLimitation> <gmd:useLimitation> <gco:CharacterString>limitation3</gco:CharacterString> </gmd:useLimitation> <gmd:accessConstraints> <gmd:MD_RestrictionCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="copyright" codeSpace="ISOTC211/19115"/> </gmd:accessConstraints> <gmd:accessConstraints> <gmd:MD_RestrictionCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="license" codeSpace="ISOTC211/19115"/> </gmd:accessConstraints> <gmd:useConstraints> <gmd:MD_RestrictionCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="copyright" codeSpace="ISOTC211/19115"/> </gmd:useConstraints> <gmd:useConstraints> <gmd:MD_RestrictionCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="license" codeSpace="ISOTC211/19115"/> </gmd:useConstraints> </gmd:MD_LegalConstraints> </gmd:resourceConstraints> <gmd:spatialRepresentationType> <gmd:MD_SpatialRepresentationTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_SpatialRepresentationTypeCode" codeListValue="vector"/> </gmd:spatialRepresentationType> <gmd:language> <gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/" codeListValue="eng" codeSpace="ISO 639-2"/> </gmd:language> <gmd:characterSet> <gmd:MD_CharacterSetCode codeList="http://www.isotc211.org/2005/resources/Codelist/ML_gmxCodelists.xml#MD_CharacterSetCode" codeListValue="utf8"/> </gmd:characterSet> <gmd:topicCategory> <gmd:MD_TopicCategoryCode>biota</gmd:MD_TopicCategoryCode> </gmd:topicCategory> <gmd:topicCategory> <gmd:MD_TopicCategoryCode>oceans</gmd:MD_TopicCategoryCode> </gmd:topicCategory> <gmd:extent> <gmd:EX_Extent> <gmd:geographicElement> <gmd:EX_GeographicBoundingBox> <gmd:extentTypeCode> <gco:Boolean>true</gco:Boolean> </gmd:extentTypeCode> <gmd:westBoundLongitude> <gco:Decimal>-180</gco:Decimal> </gmd:westBoundLongitude> <gmd:eastBoundLongitude> <gco:Decimal>180</gco:Decimal> </gmd:eastBoundLongitude> <gmd:southBoundLatitude> <gco:Decimal>-90</gco:Decimal> </gmd:southBoundLatitude> <gmd:northBoundLatitude> <gco:Decimal>90</gco:Decimal> </gmd:northBoundLatitude> </gmd:EX_GeographicBoundingBox> </gmd:geographicElement> </gmd:EX_Extent> </gmd:extent> <gmd:supplementalInformation> <gco:CharacterString>some additional information</gco:CharacterString> </gmd:supplementalInformation> </gmd:MD_DataIdentification> </gmd:identificationInfo> <gmd:contentInfo> <gmd:MD_FeatureCatalogueDescription> <gmd:complianceCode> <gco:Boolean>false</gco:Boolean> </gmd:complianceCode> <gmd:language> <gco:CharacterString>eng</gco:CharacterString> </gmd:language> <gmd:includedWithDataset> <gco:Boolean>false</gco:Boolean> </gmd:includedWithDataset> <gmd:featureCatalogueCitation> <gmd:CI_Citation> <gmd:title> <gco:CharacterString>title</gco:CharacterString> </gmd:title> <gmd:alternateTitle> <gco:CharacterString>alternate title</gco:CharacterString> </gmd:alternateTitle> <gmd:date> <gmd:CI_Date> <gmd:date> <gco:Date>2015-01-01</gco:Date> </gmd:date> <gmd:dateType> <gmd:CI_DateTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="creation" codeSpace="ISOTC211/19115"/> </gmd:dateType> </gmd:CI_Date> </gmd:date> <gmd:citedResponsibleParty> <gmd:CI_ResponsibleParty> <gmd:contactInfo> <gmd:CI_Contact> <gmd:onlineResource> <gmd:CI_OnlineResource> <gmd:linkage> <gmd:URL>http://somelink/featurecatalogue</gmd:URL> </gmd:linkage> </gmd:CI_OnlineResource> </gmd:onlineResource> </gmd:CI_Contact> </gmd:contactInfo> <gmd:role> <gmd:CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue="publisher" codeSpace="ISOTC211/19115"/> </gmd:role> </gmd:CI_Respons

>> ibleParty> </gmd:citedResponsibleParty> </gmd:CI_Citation> </gmd:featureCatalogueCitation> </gmd:MD_FeatureCatalogueDescription> </gmd:contentInfo> <gmd:distributionInfo> <gmd:MD_Distribution> <gmd:transferOptions> <gmd:MD_DigitalTransferOptions> <gmd:onLine> <gmd:CI_OnlineResource> <gmd:linkage> <gmd:URL>http://somelink1</gmd:URL> </gmd:linkage> <gmd:protocol> <gco:CharacterString>WWW:LINK-1.0-http--link</gco:CharacterString> </gmd:protocol> <gmd:name> <gco:CharacterString>name1</gco:CharacterString> </gmd:name> <gmd:description> <gco:CharacterString>description1</gco:CharacterString> </gmd:description> </gmd:CI_OnlineResource> </gmd:onLine> <gmd:onLine> <gmd:CI_OnlineResource> <gmd:linkage> <gmd:URL>http://somelink2</gmd:URL> </gmd:linkage> <gmd:protocol> <gco:CharacterString>WWW:LINK-1.0-http--link</gco:CharacterString> </gmd:protocol> <gmd:name> <gco:CharacterString>name2</gco:CharacterString> </gmd:name> <gmd:description> <gco:CharacterString>description2</gco:CharacterString> </gmd:description> </gmd:CI_OnlineResource> </gmd:onLine> <gmd:onLine> <gmd:CI_OnlineResource> <gmd:linkage> <gmd:URL>http://somelink3</gmd:URL> </gmd:linkage> <gmd:protocol> <gco:CharacterString>WWW:LINK-1.0-http--link</gco:CharacterString> </gmd:protocol> <gmd:name> <gco:CharacterString>name3</gco:CharacterString> </gmd:name> <gmd:description> <gco:CharacterString>description3</gco:CharacterString> </gmd:description> </gmd:CI_OnlineResource> </gmd:onLine> </gmd:MD_DigitalTransferOptions> </gmd:transferOptions> </gmd:MD_Distribution> </gmd:distributionInfo> <gmd:dataQualityInfo> <gmd:DQ_DataQuality> <gmd:scope> <gmd:DQ_Scope> <gmd:level> <gmd:MD_ScopeCode codeList="http://www.isotc211.org/2005/resources/Codelist/ML_gmxCodelists.xml#MD_ScopeCode" codeListValue="dataset" codeSpace="ISOTC211/19115"/> </gmd:level> </gmd:DQ_Scope> </gmd:scope> <gmd:report> <gmd:DQ_DomainConsistency> <gmd:result> <gmd:DQ_ConformanceResult> <gmd:specification> <gmd:CI_Citation> <gmd:title> <gco:CharacterString>specification title</gco:CharacterString> </gmd:title> <gmd:alternateTitle> <gco:CharacterString>specification alternate title</gco:CharacterString> </gmd:alternateTitle> <gmd:date> <gmd:CI_Date> <gmd:date> <gco:Date>2015-01-01</gco:Date> </gmd:date> <gmd:dateType> <gmd:CI_DateTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication" codeSpace="ISOTC211/19115"/> </gmd:dateType> </gmd:CI_Date> </gmd:date> </gmd:CI_Citation> </gmd:specification> <gmd:explanation> <gco:CharacterString>some explanation about the conformance</gco:CharacterString> </gmd:explanation> <gmd:pass> <gco:Boolean>true</gco:Boolean> </gmd:pass> </gmd:DQ_ConformanceResult> </gmd:result> </gmd:DQ_DomainConsistency> </gmd:report> <gmd:lineage> <gmd:LI_Lineage> <gmd:statement> <gco:CharacterString>statement</gco:CharacterString> </gmd:statement> </gmd:LI_Lineage> </gmd:lineage> </gmd:DQ_DataQuality> </gmd:dataQualityInfo></gmd:MD_Metadata>]]></data><group>1</group><category>datasets</category><stylesheet>_none_</stylesheet><validate>off</validate></request>

<- HTTP/1.1 500 
<- Server: nginx/1.19.2
<- Date: Tue, 05 Jan 2021 10:29:01 GMT
<- Content-Type: application/xml;charset=UTF-8
<- Transfer-Encoding: chunked
<- Connection: keep-alive
<- Set-Cookie: serverTime=1609842541285; Path=/
<- Set-Cookie: sessionExpiry=1609844641285; Path=/
<- X-Frame-Options: DENY
<- Content-Security-Policy: frame-ancestors 'none'
<- Pragma: no-cache
<- Cache-Control: no-cache
<- Expires: -1
<- Strict-Transport-Security: max-age=16070400; includeSubDomains
<- 
Internal Server Error (HTTP 500).[geonapi][ERROR] <?xml version="1.0" encoding="UTF-8"?>
<error id="error">
  <message>could not execute batch; SQL [insert into Metadata (data, changeDate, createDate, displayorder, doctype, extra, popularity, rating, root, schemaId, title, isTemplate, isHarvested, harvestUri, harvestUuid, groupOwner, owner, source, uuid, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [uk_e9w46i6v429h02tmynm3eefiy]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch</message>
  <class>DataIntegrityViolationException</class>
  <stack>
    <at class="org.springframework.orm.jpa.vendor.HibernateJpaDialect" file="HibernateJpaDialect.java" line="278" method="convertHibernateAccessException"/>
    <at class="org.springframework.orm.jpa.vendor.HibernateJpaDialect" file="HibernateJpaDialect.java" line="244" method="translateExceptionIfPossible"/>
    <at class="org.springframework.orm.jpa.AbstractEntityManagerFactoryBean" file="AbstractEntityManagerFactoryBean.java" line="491" method="translateExceptionIfPossible"/>
    <at class="org.springframework.dao.support.ChainedPersistenceExceptionTranslator" file="ChainedPersistenceExceptionTranslator.java" line="59" method="translateExceptionIfPossible"/>
    <at class="org.springframework.dao.support.DataAccessUtils" file="DataAccessUtils.java" line="213" method="translateIfNecessary"/>
    <at class="org.springframework.dao.support.PersistenceExceptionTranslationInterceptor" file="PersistenceExceptionTranslationInterceptor.java" line="147" method="invoke"/>
    <at class="org.springframework.aop.framework.ReflectiveMethodInvocation" file="ReflectiveMethodInvocation.java" line="179" method="proceed"/>
    <at class="org.springframework.data.jpa.repository.support.LockModeRepositoryPostProcessor$LockModePopulatingMethodIntercceptor" file="LockModeRepositoryPostProcessor.java" line="92" method="invoke"/>
    <at class="org.springframework.aop.framework.ReflectiveMethodInvocation" file="ReflectiveMethodInvocation.java" line="179" method="proceed"/>
    <at class="org.springframework.aop.interceptor.ExposeInvocationInterceptor" file="ExposeInvocationInterceptor.java" line="92" method="invoke"/>
    <skip>...</skip>
    <at class="org.fao.geonet.kernel.datamanager.base.BaseMetadataUtils" file="BaseMetadataUtils.java" line="926" method="exists"/>
    <at class="org.fao.geonet.kernel.datamanager.draft.DraftMetadataUtils" file="DraftMetadataUtils.java" line="260" method="findOne"/>
    <at class="org.fao.geonet.kernel.datamanager.base.BaseMetadataOperations" file="BaseMetadataOperations.java" line="181" method="forceSetOperation"/>
    <at class="org.fao.geonet.kernel.datamanager.base.BaseMetadataOperations" file="BaseMetadataOperations.java" line="153" method="setOperation"/>
    <at class="org.fao.geonet.kernel.datamanager.base.BaseMetadataOperations" file="BaseMetadataOperations.java" line="123" method="setOperation"/>
    <at class="org.fao.geonet.kernel.datamanager.base.BaseMetadataOperations" file="BaseMetadataOperations.java" line="340" method="copyDefaultPrivForGroup"/>
    <at class="org.fao.geonet.kernel.datamanager.base.BaseMetadataManager" file="BaseMetadataManager.java" line="629" method="insertMetadata"/>
    <at class="org.fao.geonet.kernel.datamanager.base.BaseMetadataManager" file="BaseMetadataManager.java" line="588" method="insertMetadata"/>
    <at class="org.fao.geonet.kernel.datamanager.base.BaseMetadataManager$$FastClassBySpringCGLIB$$3a6cdaae" file="&lt;generated&gt;" line="-1" method="invoke"/>
    <skip>...</skip>
    <at class="org.fao.geonet.kernel.datamanager.draft.DraftMetadataManager$$EnhancerBySpringCGLIB$$505e3c70" file="&lt;generated&gt;" line="-1" method="insertMetadata"/>
    <at class="org.fao.geonet.kernel.mef.Importer" file="Importer.java" line="550" method="importRecord"/>
    <at class="org.fao.geonet.services.metadata.Insert" file="Insert.java" line="145" method="serviceSpecificExec"/>
    <at class="org.fao.geonet.services.NotInReadOnlyModeService" file="NotInReadOnlyModeService.java" line="54" method="exec"/>
    <at class="jeeves.server.dispatchers.ServiceInfo" file="ServiceInfo.java" line="227" method="execService"/>
    <at class="jeeves.server.dispatchers.ServiceInfo" file="ServiceInfo.java" line="142" method="noTransactionExec"/>
    <at class="jeeves.server.dispatchers.ServiceInfo" file="ServiceInfo.java" line="46" method="access$000"/>
    <at class="jeeves.server.dispatchers.ServiceInfo$1" file="ServiceInfo.java" line="121" method="doInTransaction"/>
    <at class="jeeves.server.dispatchers.ServiceInfo$1" file="ServiceInfo.java" line="118" method="doInTransaction"/>
    <at class="jeeves.transaction.TransactionManager" file="TransactionManager.java" line="73" method="runInTransaction"/>
    <at class="jeeves.server.dispatchers.ServiceInfo" file="ServiceInfo.java" line="115" method="execServices"/>
    <at class="jeeves.server.dispatchers.ServiceManager" file="ServiceManager.java" line="449" method="dispatch"/>
    <at class="jeeves.server.dispatchers.ServiceManager" file="ServiceManager.java" line="387" method="dispatch"/>
    <at class="jeeves.server.JeevesEngine" file="JeevesEngine.java" line="593" method="dispatch"/>
    <at class="org.fao.geonet.services.main.GenericController" file="GenericController.java" line="160" method="dispatch"/>
    <skip>...</skip>
    <at class="jeeves.config.springutil.JeevesDispatcherServlet" file="JeevesDispatcherServlet.java" line="44" method="access$101"/>
    <at class="jeeves.config.springutil.JeevesDispatcherServlet$1" file="JeevesDispatcherServlet.java" line="56" method="doInTransaction"/>
    <at class="jeeves.config.springutil.JeevesDispatcherServlet$1" file="JeevesDispatcherServlet.java" line="52" method="doInTransaction"/>
    <at class="jeeves.transaction.TransactionManager" file="TransactionManager.java" line="73" method="runInTransaction"/>
    <at class="jeeves.config.springutil.JeevesDispatcherServlet" file="JeevesDispatcherServlet.java" line="49" method="doDispatch"/>
    <skip>...</skip>
    <at class="org.fao.geonet.web.CORSResponseFilter" file="CORSResponseFilter.java" line="129" method="doFilter"/>
    <skip>...</skip>
    <at class="org.fao.geonet.monitor.webapp.WebappMetricsFilter" file="WebappMetricsFilter.java" line="121" method="doFilter"/>
    <skip>...</skip>
    <at class="org.fao.geonet.monitor.webapp.MetricsRegistryInitializerFilter" file="MetricsRegistryInitializerFilter.java" line="58" method="doFilter"/>
    <skip>...</skip>
    <at class="org.fao.geonet.web.XFrameOptionsFilter" file="XFrameOptionsFilter.java" line="110" method="doFilter"/>
    <skip>...</skip>
    <at class="org.geonetwork.http.SessionTimeoutCookieFilter" file="SessionTimeoutCookieFilter.java" line="91" method="doFilter"/>
    <skip>...</skip>
    <at class="jeeves.config.springutil.PassthroughFilter" file="PassthroughFilter.java" line="50" method="doFilter"/>
    <skip>...</skip>
    <at class="jeeves.config.springutil.JeevesDelegatingFilterProxy" file="JeevesDelegatingFilterProxy.java" line="104" method="doFilter"/>
    <skip>...</skip>
  </stack>
  <request>
    <language>eng</language>
    <service>xml.metadata.insert</service>
  </request>
</error>

**Comment by LuciaSegovia** [comment]
There is a part that it doesn't show, I am not sure why... (Sorry, I'm quite new on this...)

**Comment by eblondel** [comment]
Do you know the version of the Geonetwork you use?

**Comment by LuciaSegovia** [comment]
It's 'GeoNetwork 3.10.4.0'

**Comment by eblondel** [comment]
Is your geonetwork available on the web so I can test? In case you can share with me the info by email.

**Comment by LuciaSegovia** [comment]
I've just sent you an email :)

**Comment by LuciaSegovia** [comment]
Hi @eblondel!

It worked!! I can add metadata now using your package! 

Thanks v much!!

**Comment by eblondel** [comment]
Great to hear this @LuciaSegovia , thanks for reporting :-)
