### ISSUE TITLE
Error while getting metadata with GN 3.10.6

### ISSUE THREAD

**Issue by juliettefabre** [eblondel/geonapi#12]
Hi,
We upgraded our GeoNetwork from 3.0.3 to 3.10.6. Now I get errors when I fetch metadata with the _get_ method:

```
> GN <- GNManager$new(url = gn_url, version = "3.10.6.0", user = "xxx", pwd = "xxx", logger = "INFO")
> md_identifier <- "8dbdb4d7-161a-45e3-b3c3-51e6058f6e8a"
> metaId <- GN$get(md_identifier, by = "uuid", output = "id")
[geonapi][INFO] Fetching metadata for uuid = 8dbdb4d7-161a-45e3-b3c3-51e6058f6e8a 
[geonapi][INFO] Successfully fetched metadata! 
Error in GN$get(md_identifier, by = "uuid", output = "id") : 
  No geonet:info XML element found
```

Any idea?

Moreover fetching metadata with the _getMetadataByUUID_ method is successful but takes a looong time (4 min).

Thanks!
Juliette

**Comment by eblondel** [comment]
geonapi works with the legacy API. You need to active the geonet:info XML block.
THis can be done setting a file /etc/geonetwork/config-view-service-override.xml (see https://github.com/eblondel/geonapi/blob/master/tests/resources/config-view-service-override.xml) that specifies skipInfo = 'n' in the `*/WEB-INF/config/config-service-xml-api.xml` service for `xml.metadata.get` operation.

Check with @wheintz he can help you configuring it

**Comment by juliettefabre** [comment]
Thank you, I'll try it asap!

**Comment by eblondel** [comment]
@juliettefabre any news on that? did you try the above tip?

**Comment by juliettefabre** [comment]
Didn't have the time yet! I'll keep you in touch as soon as i tried it.

**Comment by juliettefabre** [comment]
Hi,
I set a /etc/geonetwork/config-view-service-override.xml file.
I pasted the code you provided and filled the `filename=""` with the absolute path of the `config-service-xml-api.xml` file (*):

```
<overrides xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="config-overrides.xsd">
  <file name="/var/lib/tomcat9/webapps/geonetwork/WEB-INF/config/config-service-xml-api.xml">
    <replaceAtt xpath="services/service[@name='xml.metadata.get']/class/param[@name='skipInfo']"
                attName="value" value="n"/>
  </file>
</overrides>
```
I restarted GN but I still get the error: 
```
Error in GN$get(md_identifier, by = "uuid", output = "id") :
  No geonet:info XML element found
```
(*) Initially I put the code you provided without changing the `filename` part. But the result was the same.

I checked with @wheintz but this configuration isn't familiar to him. He got the same error by trying to request my GN with him geonapi.

I upgraded geonapi (0.2 -> 0.4) and geometa (0.5 -> 0.6-4) but the problem persists ..

**Comment by eblondel** [comment]
This doesn't deal with R packages. The message ` No geonet:info XML element found` indicates that the geonet:info is not configured in XML get service. Can you try to locate you `config-service-xml-api.xml`? (and send me a copy - by email - to look at it)

**Comment by wheintz** [comment]
Hi Juliette & Emmanuel,

Indeed, I found something in my configuration! Forgot to use sudo last time, sorry ;-)

Juliette, in your GN tomcat configuration directory (eg. /var/lib/tomcat8/webapps/geonetwork/WEB-INF/config/config-service-xml-api.xml for me) you have to change param "skipInfo" to "n" ("y" by default) in <service name="xml.metadata.get" xmlapi="true">
block.

Tell me if it's not clear ;-)

Cheers.

**Comment by juliettefabre** [comment]
Hi,
Thanks Wilfried, it works! 
But I don't understand: for me the /etc/geonetwork/config-view-service-override.xml file that Emmanuel set was supposed to override the _skipInfo_ parameter value and to change it to "n" .. 
Anyway, it's OK now, thanks a lot to both of you.
Juliette

**Comment by eblondel** [comment]
Thanks @juliettefabre in case you face issues with Geonetwork 3.10.6 let me know.
