### ISSUE TITLE
Error with the generic getter with GN 3.10.6

### ISSUE THREAD

**Issue by juliettefabre** [eblondel/geonapi#17]
Hi @eblondel,

With GeoNetwork 3.10.6 and geonapi 1.5.0 and 1.5.1 I get an error when trying to fetch the metadata id for a given uuid :

```
metaId <- GN$get(md_identifier, by = "uuid", output = "id")
Erreur dans GN$get(md_identifier, by = "uuid", output = "id") : 
  tentative d'appliquer un objet qui n'est pas une fonction
```

I use it to know if a given metadata already exists in GN or not, then I update or I insert metadata. It used to work well.

I tried to insert metadata instead of updating it, as I found that the `insertMetadata` method now takes a `uuidProcessing` parameter.
But I didn't find any mention of this parameter in the documentation, and I can't get its different values. How I can I overwrite/update metadata for a given uuid?

Thanks!
Juliette

**Comment by eblondel** [comment]
From geonapi 0.5, the package manages 2 different Geonetwork managers depending on the GN version. For GN > 3.2 geonapi switchs from the legacy API to the Open API. In the latter, the same `insertRecord` should be used. Update strategy is indicated by the `uuidProcessing` that you can set to "OVERWRITE". GN will manage the insert/update strategy for you. See the code example as implemented in [geoflow](https://github.com/eblondel/geoflow): https://github.com/eblondel/geoflow/blob/master/R/geoflow_action_geonapi_publish_iso_19139.R#L66

I checked the doc and indeed it deserves some consolidation to explain parameters in particular `uuidProcessing`

**Comment by juliettefabre** [comment]
Thanks!
