### ISSUE TITLE
Error with GN login with GN 3.10.3

### ISSUE THREAD

**Issue by Davien44** [eblondel/geonapi#20]
Hi,

I'm trying to connect to a GeoNetwork (version 3.10.3) with the folowing parameters:

` > GN <- GNManager$new(url = "gn_url", version = "3.10.3", user = "xxx", pwd = "xxx", logger = "DEBUG")`

But I have this error, and I don't really understand where it come from:

`Error in curl::curl_fetch_memory(url, handle = handle) : 
  Maximum (10) redirects followed`

I tried to connect to another GeoNetwork (version 3.12.2) and it works perfectly.

Do you have any idea where the error might come from?

Thanks,
Davien

**Comment by eblondel** [comment]
Without a test, I can assert anything. I could get similar issues with a geonetwork trying to get the url as http, although it was supposed to be in https. From 3.12, the GNManager will now switch to the new API, although before the legacy API is used. I don't exclude some intermediate logics to 3.10.x series have been skipped with geonapi.
If you can send me a test case (by email), with a test user assigned, i'll be able to test and debug.

**Comment by eblondel** [comment]
@Davien44 can you reinstall and check if #21 fixes the issue?

**Comment by eblondel** [comment]
Fixed with #21
